name: 'Install R package dependencies'
description: 'Installs and caches the R package dependencies based on a DESCRIPTION file'
inputs:
  os-runner:
    description: 'os.runner'
    required: true
  linux-version:
    description: 'Linux version to target'
    required: true
    default: '16.04'
runs:
  using: "composite"
  steps:
      - name: Install pak
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
        shell: Rscript {0}

      - name: Install system dependencies
        run: |
          while read -r cmd
          do
            eval sudo $cmd
            done < <(Rscript -e "if ('${{ inputs.os-runner }}' == 'Linux') writeLines(pak::local_system_requirements('ubuntu', '${{ inputs.linux-version }}')))")
        shell: bash

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps()
          pak::pkg_install("rcmdcheck")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
