on:
  push:
    branches: [main, master, v2-branch]
  pull_request:
    branches: [main, master, v2-branch]
  workflow_dispatch:

name: "setup-tinytex test"

jobs:
  tinytex:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest   }
          - { os: windows-latest }
          - { os: ubuntu-latest  }

    steps:
      - uses: actions/checkout@v4

      - uses: ./setup-tinytex
        env:
          TINYTEX_INSTALLER: TinyTeX
          TINYTEX_VERSION: 2024.02

      - run: tlmgr --version

      - run: tlmgr install colortbl grfext ae
