on:
  push:
    branches: [main, master, v2-branch]
  pull_request:
    branches: [main, master, v2-branch]
  workflow_dispatch:
    
name: "setup-tinytex test"

jobs:
  tinytex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-tinytex@v2-branch
        env:
          # always install the bundled version from Nov. 2021
          TINYTEX_VERSION: 2021.11

      - run: tlmgr --version
